apiVersion: v1
kind: Service
metadata:
  name: bank-transactions-service
spec:
  selector:
    app: bank-transactions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transactions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-transactions
  template:
    metadata:
      labels:
        app: bank-transactions
    spec:
      containers:
        - name: bank-transactions
          image: zeusmarval/bank-transactions:latest
          ports:
            - containerPort: 8086